# Generated by Django 4.0.4 on 2022-04-14 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimg',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='gallery.galleryimg'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='gallery.galleryvideo'),
        ),
    ]
