# Generated by Django 4.0.4 on 2022-04-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_postimg_gallery_alter_postvideo_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimg',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_i', to='gallery.post'),
        ),
        migrations.AlterField(
            model_name='galleryvideo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_v', to='gallery.post'),
        ),
    ]
