# Generated by Django 4.0.4 on 2022-04-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryimg_post_alter_galleryvideo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimg',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_img', to='gallery.post'),
        ),
        migrations.AlterField(
            model_name='galleryvideo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_video', to='gallery.post'),
        ),
    ]
